### ISSUE TITLE
[Feature Request] Icons for Toys

### ISSUE THREAD

**Issue by yozhic** [PederBirk/Flow.Launcher.Plugin.PowerToys#2]
Please, could you add a feature to display icons for toys (apps) like _PowerToys Run_ does?  

![GreenShot-20240919_154227](https://github.com/user-attachments/assets/fb0ca2eb-c68c-4607-b863-a2cefb7daf22)

All toy icons are located here:  

```
%AppData%\Local\PowerToys\WinUI3Apps\Assets\Settings\Icons\*.png
```

**Comment by PederBirk** [comment]
The apps do have icons, but they are loaded from the PowerToys github repo. So they will only show if you are connected to the internet. I would prefer not to ship the icons in this plugin, as they are not mine. Closing this as a won't do.

**Comment by yozhic** [comment]
Okay, if you don't want to do it, I respect your decision.

But I don't understand the reasoning. You download icons from the internet from the PowerToys repository. But why go that far? The **same icons** are much closer, in the PowerToys installation folder. Not in your plugin folder, but in the PowerToys program folder:
![GreenShot-20240920_102307](https://github.com/user-attachments/assets/44988310-83ed-4c09-b542-66e73ab09fef)
We don't staff your plugin with icons, we just load icons from the local PowerToys location just like we load them from the remote PowerToys location.
